### ISSUE TITLE
Test on data error

### ISSUE THREAD

**Issue by willw1** [guillaumelenoir/WAVEPAL#12]
On Ubuntu 18, installed boost 1.59 and appears to build ok, but fails during tests, the last part of the output is:

SECOND ROUND: generates  16000  samples
***************************************
Running sampler...
Number of steps added: 1
Number of tracked steps added: 1
Setting starting values...
 Drawn from priors
 ...Initializing    0.2699
   0.9582
  -0.0003
  -5.7993

Burning in... (8000 iterations)

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**************************************************Average RAM Acceptance Rate is 0.275125
*

Sampling...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Calculating sigma...
Calculating log-likelihoods...
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    x.carma_params(make_carma_fig=True,nbins=20,dpi=400,path_to_figure_folder=path_to_figure_folder)
  File "build/bdist.linux-x86_64/egg/wavepal/Wavepal.py", line 653, in carma_params
TypeError: assess_fit() takes at most 4 arguments (12 given)

**Comment by guillaumelenoir** [comment]
Hi,
If you have a look at WAVEPAL/carmcmc/carma_pack, line 693, it has more than 4 arguments, so that if all is properly installed with the right paths, it should work.
This part of code is a modified version of another package, called CARMA PACK. If you have this package already installed on your computer, you should delete it, and let WAVEPAL reinstall it correctly. 
Do not hesitate to get in touch if it does not work.  
Cheers,
Guillaume.

**Comment by Cornelius43** [comment]
Hi,
I have the same problem. I dont find a CARMA PACK...where I have to search. Ehat fix the problem?
Cheers,
Cornelius
